package br.pucminas.aluguel.controller;

import br.pucminas.aluguel.model.*;
import br.pucminas.aluguel.service.AluguelService;
import br.pucminas.aluguel.view.HtmlView;
import com.sun.net.httpserver.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class AluguelController {
    private final AluguelService service;
    private final HtmlView view;
    private final Map<String, Cliente> sessoes = new HashMap<>();
    public AluguelController(AluguelService service, HtmlView view) { this.service = service; this.view = view; }
    public void registrar(HttpExchange exchange) throws IOException { if ("GET".equals(exchange.getRequestMethod())) { responder(exchange, view.cadastro(null)); return; } try { Map<String,String> f = campos(exchange); Cliente c = service.cadastrar(f.get("login"), f.get("senha"), f.get("rg"), f.get("cpf"), f.get("nome"), f.get("endereco"), f.get("profissao")); iniciar(exchange, c); redirecionar(exchange, "/pedidos"); } catch (RuntimeException e) { responder(exchange, view.cadastro(e.getMessage())); } }
    public void login(HttpExchange exchange) throws IOException { if ("GET".equals(exchange.getRequestMethod())) { responder(exchange, view.login(null)); return; } Map<String,String> f = campos(exchange); Cliente c = service.autenticar(f.get("login"), f.get("senha")); if (c == null) responder(exchange, view.login("Login ou senha inválidos.")); else { iniciar(exchange, c); redirecionar(exchange, "/pedidos"); } }
    public void pedidos(HttpExchange exchange) throws IOException { Cliente c = cliente(exchange); if (c == null) { redirecionar(exchange, "/login"); return; } responder(exchange, view.dashboard(c, service.pedidosDo(c), service.automoveis(), null)); }
    public void pedido(HttpExchange exchange) throws IOException { Cliente c = cliente(exchange); if (c == null) { redirecionar(exchange, "/login"); return; } try { Map<String,String> f = campos(exchange); service.criarPedido(c, Long.parseLong(f.get("automovel")), Modalidade.valueOf(f.get("modalidade"))); redirecionar(exchange, "/pedidos"); } catch (RuntimeException e) { responder(exchange, view.dashboard(c, service.pedidosDo(c), service.automoveis(), e.getMessage())); } }
    public void empregadora(HttpExchange exchange) throws IOException { Cliente c = cliente(exchange); if (c == null) { redirecionar(exchange, "/login"); return; } try { Map<String,String> f = campos(exchange); service.adicionarEmpregadora(c, f.get("nome"), Double.parseDouble(f.get("rendimento"))); redirecionar(exchange, "/pedidos"); } catch (RuntimeException e) { responder(exchange, view.dashboard(c, service.pedidosDo(c), service.automoveis(), e.getMessage())); } }
    public void gerenciarCliente(HttpExchange exchange) throws IOException { Cliente c = cliente(exchange); if (c == null) { redirecionar(exchange, "/login"); return; } try { Map<String,String> f = campos(exchange); if ("DELETE".equals(f.get("_method"))) { service.excluirCliente(c); logout(exchange); return; } service.atualizarCliente(c, f.get("rg"), f.get("nome"), f.get("endereco"), f.get("profissao")); redirecionar(exchange, "/pedidos"); } catch (RuntimeException e) { responder(exchange, view.dashboard(c, service.pedidosDo(c), service.automoveis(), e.getMessage())); } }
    public void cancelar(HttpExchange exchange) throws IOException { Cliente c = cliente(exchange); if (c == null) { redirecionar(exchange, "/login"); return; } try { service.cancelar(c, Long.parseLong(campos(exchange).get("numero"))); redirecionar(exchange, "/pedidos"); } catch (RuntimeException e) { responder(exchange, view.dashboard(c, service.pedidosDo(c), service.automoveis(), e.getMessage())); } }
    public void alterar(HttpExchange exchange) throws IOException { Cliente c = cliente(exchange); if (c == null) { redirecionar(exchange, "/login"); return; } try { Map<String,String> f = campos(exchange); service.alterar(c, Long.parseLong(f.get("numero")), Long.parseLong(f.get("automovel")), Modalidade.valueOf(f.get("modalidade"))); redirecionar(exchange, "/pedidos"); } catch (RuntimeException e) { responder(exchange, view.dashboard(c, service.pedidosDo(c), service.automoveis(), e.getMessage())); } }
    public void decidir(HttpExchange exchange) throws IOException { Cliente c = cliente(exchange); if (c == null) { redirecionar(exchange, "/login"); return; } try { Map<String,String> f = campos(exchange); service.decidir(c, Long.parseLong(f.get("numero")), "aceitar".equals(f.get("decisao"))); redirecionar(exchange, "/pedidos"); } catch (RuntimeException e) { responder(exchange, view.dashboard(c, service.pedidosDo(c), service.automoveis(), e.getMessage())); } }
    public void agente(HttpExchange exchange) throws IOException { responder(exchange, view.agente(service.pedidosEmAnalise(), service.automoveis(), null)); }
    public void avaliar(HttpExchange exchange) throws IOException { try { Map<String,String> f = campos(exchange); service.avaliar(Long.parseLong(f.get("numero")), "aprovar".equals(f.get("resultado")), f.get("justificativa")); redirecionar(exchange, "/agente"); } catch (RuntimeException e) { responder(exchange, view.agente(service.pedidosEmAnalise(), service.automoveis(), e.getMessage())); } }
    public void automovel(HttpExchange exchange) throws IOException { try { Map<String,String> f = campos(exchange); service.cadastrarAutomovel(f.get("placa"), Integer.parseInt(f.get("ano")), f.get("marca"), f.get("modelo")); redirecionar(exchange, "/agente"); } catch (RuntimeException e) { responder(exchange, view.agente(service.pedidosEmAnalise(), service.automoveis(), e.getMessage())); } }
    public void logout(HttpExchange exchange) throws IOException { String token = cookie(exchange, "SESSION"); if (token != null) sessoes.remove(token); exchange.getResponseHeaders().add("Set-Cookie", "SESSION=; Max-Age=0; Path=/"); redirecionar(exchange, "/"); }
    private Cliente cliente(HttpExchange e) { String token = cookie(e, "SESSION"); return token == null ? null : sessoes.get(token); }
    private void iniciar(HttpExchange e, Cliente c) { String token = UUID.randomUUID().toString(); sessoes.put(token, c); e.getResponseHeaders().add("Set-Cookie", "SESSION=" + token + "; Path=/; HttpOnly"); }
    private Map<String,String> campos(HttpExchange e) throws IOException { String body = new String(e.getRequestBody().readAllBytes(), StandardCharsets.UTF_8); Map<String,String> result = new HashMap<>(); for (String item : body.split("&")) { String[] pair = item.split("=", 2); if (pair.length == 2) result.put(URLDecoder.decode(pair[0], StandardCharsets.UTF_8), URLDecoder.decode(pair[1], StandardCharsets.UTF_8)); } return result; }
    private String cookie(HttpExchange e, String name) { String header = e.getRequestHeaders().getFirst("Cookie"); if (header == null) return null; for (String item : header.split(";")) { String[] pair = item.trim().split("=", 2); if (pair.length == 2 && pair[0].equals(name)) return pair[1]; } return null; }
    private void responder(HttpExchange e, String body) throws IOException { byte[] bytes = body.getBytes(StandardCharsets.UTF_8); e.getResponseHeaders().set("Content-Type", "text/html; charset=UTF-8"); e.sendResponseHeaders(200, bytes.length); try (OutputStream out = e.getResponseBody()) { out.write(bytes); } }
    private void redirecionar(HttpExchange e, String path) throws IOException { e.getResponseHeaders().add("Location", path); e.sendResponseHeaders(303, -1); e.close(); }
}